export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INGREDIENTS_RECEIVED = 'INGREDIENTS_RECEIVED';
export const INGREDIENTS_RECEIVED_FAILED = 'INGREDIENTS_RECEIVED_FAILED';
export const INGREDIENT_PRICES_RECEIVED = 'INGREDIENT_PRICES_RECEIVED';
export const INGREDIENT_PRICES_RECEIVED_FAILED =
  'INGREDIENT_PRICES_RECEIVED_FAILED';
