export const RESET_BURGER = 'RESET_BURGER';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const INGREDIENTS_RECEIVED = 'INGREDIENTS_RECEIVED';
export const INGREDIENTS_RECEIVED_FAILED = 'INGREDIENTS_RECEIVED_FAILED';

export const FETCH_INGREDIENT_PRICES = 'FETCH_INGREDIENT_PRICES';
export const INGREDIENT_PRICES_RECEIVED = 'INGREDIENT_PRICES_RECEIVED';
export const INGREDIENT_PRICES_RECEIVED_FAILED =
  'INGREDIENT_PRICES_RECEIVED_FAILED';

export const PLACE_ORDER_START = 'PLACE_ORDER_START';
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_SUCCESSFUL = 'PLACE_ORDER_SUCCESSFUL';
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';

export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESSFUL = 'GET_ORDERS_SUCCESSFUL';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

export const USER_SIGNUP_START_SAGA = 'USER_SIGNUP_START_SAGA';
export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const USER_LOGIN_START_SAGA = 'USER_LOGIN_START_SAGA';
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT = 'USER_LOGOUT';

export const TOKEN_REFRESH_START_SAGA = 'TOKEN_REFRESH_START_SAGA';
export const TOKEN_REFRESH_START = 'TOKEN_REFRESH_START';
export const TOKEN_REFRESH_FAILED = 'TOKEN_REFRESH_FAILED';
export const TOKEN_CHECK_START = 'TOKEN_CHECK_START';

export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';
