export const RESET_BURGER = 'RESET_BURGER';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INGREDIENTS_RECEIVED = 'INGREDIENTS_RECEIVED';
export const INGREDIENTS_RECEIVED_FAILED = 'INGREDIENTS_RECEIVED_FAILED';
export const INGREDIENT_PRICES_RECEIVED = 'INGREDIENT_PRICES_RECEIVED';
export const INGREDIENT_PRICES_RECEIVED_FAILED =
  'INGREDIENT_PRICES_RECEIVED_FAILED';

export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_SUCCESSFUL = 'PLACE_ORDER_SUCCESSFUL';
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';
export const ORDERS_RECEIVED = 'ORDERS_RECEIVED';

export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
